# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: moogle905 # jekyll-seo-tag > Owners twitter username
author: matthew-robertson # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Matt Robertson # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/DavidDarnes
    - https://www.facebook.com/daviddarnes
    - https://www.linkedin.com/in/daviddarnes
    - https://plus.google.com/+DavidDarnes
    - https://github.com/daviddarnes
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Alembic" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Vorebot is a Discord bot designed to shame your server's members for making vore references" # Site description and default description, also used in jekyll-seo-tag
url: "http://vorebot.xyz" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "http://github.com/matthew-robertson/banned-word-bot"
email: "bot@vorebot.xyz"
# google_analytics: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site navigation
navigation_header:
  Home: /
  Support: https://discordapp.com/invite/nUZsfYS
  Commands: /commands/
  About: /about/

navigation_footer:
  Created by Matt: http://mattrobertson.ca

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/DavidDarnes
  LinkedIn: https://www.linkedin.com/in/daviddarnes
  Google+: https://plus.google.com/+DavidDarnes
  GitHub: https://github.com/daviddarnes
  link: https://darn.es
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
